services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.5-ce.0
    container_name: gitlab
    restart: "no"
    hostname: gitlab.mgkim.net
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.mgkim.net'
    ports:
      - '8090:80'
      - '8022:22'
    volumes:
      - /data/gitlab/data:/var/opt/gitlab
      - /data/gitlab/conf:/etc/gitlab
      - /data/gitlab/logs:/var/log/gitlab
    shm_size: '256m'
