services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.19-bleeding
    restart: always
    container_name: gitlab-runner
    ports:
      - 8093:8093
    volumes:
      - gitlab-runner_conf:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-default

volumes:
  gitlab-runner_conf:

networks:
  local-default:
    external: true
