services:
  jenkins:
    image: jenkins/jenkins:2.496-jdk17
    restart: unless-stopped
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - local-default

volumes:
  jenkins_data:

networks:
  local-default:
    external: true
