services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=1
    volumes:
      - mariadb_data:/var/lib/mysql
    network_mode: host
    #networks:
    #  - local-default

volumes:
  mariadb_data:

networks:
  local-default:
    external: true
