services:
  mattermost:
    image: mattermost/mattermost-team-edition:release-10.3
    container_name: mattermost
    restart: unless-stopped
    ports:
      - 8065:8065
      - 8443:8443/udp
      - 8443:8443/tcp
    environment:
      - TZ=UTC
      - MM_USERNAME=admin
      - MM_EMAIL=lislroow@daum.com
      - MM_PASSWORD=trustno1
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres:1@postgresql:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=https://mm.mgkim.net
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - mattermost_config:/mattermost/config:rw
      - mattermost_data:/mattermost/data:rw
      - mattermost_logs:/mattermost/logs:rw
      - mattermost_plugins:/mattermost/plugins:rw
      - mattermost_client-plugins:/mattermost/client/plugins:rw
      - mattermost_bleve-indexes:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority 
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro
    networks:
      - local-default

  mattermost-nginx:
    depends_on:
      - mattermost
    container_name: mattermost-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    environment:
      - TZ=UTC
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ./mattermost/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./mattermost/nginx/dhparams4096.pem:/dhparams4096.pem
      - ./mattermost/nginx/webroot:/usr/share/nginx/html
      - /etc/letsencrypt/live/mm.mgkim.net/fullchain.pem:/cert.pem:ro
      - /etc/letsencrypt/live/mm.mgkim.net/privkey.pem:/key.pem:ro
    networks:
      - local-default

volumes:
  mattermost_config:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client-plugins:
  mattermost_bleve-indexes:

networks:
  local-default:
    external: true
