services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 443:443
      - 5000:5000
      - 80:80
    environment:
      - TZ=UTC
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/dhparams4096.pem:/dhparams4096.pem
      - ./nginx/webroot:/usr/share/nginx/html
      - /etc/letsencrypt/live/mm.mgkim.net/fullchain.pem:/cert_mm.mgkim.net.pem:ro
      - /etc/letsencrypt/live/mm.mgkim.net/privkey.pem:/key_mm.mgkim.net.pem:ro
      - /etc/letsencrypt/live/nexus.mgkim.net/fullchain.pem:/cert_nexus.mgkim.net.pem:ro
      - /etc/letsencrypt/live/nexus.mgkim.net/privkey.pem:/key_nexus.mgkim.net.pem:ro
      - /etc/letsencrypt/live/docker.mgkim.net/fullchain.pem:/cert_docker.mgkim.net.pem:ro
      - /etc/letsencrypt/live/docker.mgkim.net/privkey.pem:/key_docker.mgkim.net.pem:ro
      - /etc/letsencrypt/live/gitlab.mgkim.net/fullchain.pem:/cert_gitlab.mgkim.net.pem:ro
      - /etc/letsencrypt/live/gitlab.mgkim.net/privkey.pem:/key_gitlab.mgkim.net.pem:ro
    networks:
      - local-default

networks:
  local-default:
    external: true
