services:
  postgresql:
    container_name: postgresql
    image: postgres:14.18
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    network_mode: host
    #networks:
    #  - local-default

volumes:
  postgresql_data:

networks:
  local-default:
    external: true
