apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins   # Deployment 의 label 과 일치해야 함
  ports:
    - protocol: TCP
      port: 8080        # Service 가 노출하는 port
      targetPort: 8080  # Pod 내부 Jenkins 컨테이너가 listen 중인 port