apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
      nodePort: 30801
    - name: docker
      port: 5000
      targetPort: 5000
      nodePort: 30500
