services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRES_HOST=172.28.200.101
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=${POSTGRES_DB}
      - DB_POSTGRES_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    container_name: n8n
    ports:
      - 5678:5678
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    network_mode: host

volumes:
  n8n_data:
  n8n_db:

networks:
  local-default:
    external: true
