services:
  n8n_postgres:
    image: postgres:16
    container_name: n8n_postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    restart: always
    ports:
      - 15432:5432
    volumes:
      - n8n_db:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRES_HOST=n8n_postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=${POSTGRES_DB}
      - DB_POSTGRES_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    container_name: n8n
    ports:
      - 5678:5678
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      n8n_postgres:
        condition: service_healthy
    network_mode: host

volumes:
  n8n_data:
  n8n_db:

networks:
  local-default:
    external: true
