version: '3'
services:
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    ports:
      - 8080:8080
    restart: always
    environment:
      - DB_VENDOR: POSTGRES
      - DB_ADDR: postgres
      - DB_DATABASE: keycloak
      - DB_USER: keycloak
      - DB_SCHEMA: public
      - DB_PASSWORD: 1
      - KEYCLOAK_USER: admin
      - KEYCLOAK_PASSWORD: 1
    networks:
      - local-default

networks:
  local-default:
    external: true
