version: '3'
services:
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: 1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - local-default

volumes:
  keycloak_data:

networks:
  local-default:
    external: true
