services:
  mariadb-market-customer:
    image: mariadb:latest
    container_name: mariadb-market-customer
    ports:
      - 3401:3401
    restart: always
    volumes:
    - mariadb-market-customer_data:/var/lib/mysql
    env_file: mariadb/market-customer.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-customer_data:

networks:
  local-default:
    external: true