services:
  mariadb-market-product:
    image: mariadb:latest
    container_name: mariadb-market-product
    ports:
      - 3405:3405
    restart: no
    volumes:
      - mariadb-market-product_data:/var/lib/mysql
    env_file: mariadb/market-product.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-product_data:

networks:
  local-default:
    external: true