services:
  mariadb-market-delivery:
    image: mariadb:latest
    container_name: mariadb-market-delivery
    ports:
      - 3402:3402
    restart: always
    volumes:
      - mariadb-market-delivery_data:/var/lib/mysql
    env_file: mariadb/market-delivery.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-delivery_data:

networks:
  local-default:
    external: true