services:
  nexus:
    image: sonatype/nexus3:3.74.0
    container_name: nexus
    ports:
      - 8081:8081
      - 5000:5000
    restart: always
    environment:
      #- INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      - INSTALL4J_ADD_VM_PARAMS=-Xms256m -Xmx768m -XX:MaxDirectMemorySize=256m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - nexus_data:/nexus-data
    networks:
      - local-default

volumes:
  nexus_data:

networks:
  local-default:
    external: true
