services:
  nexus:
    image: sonatype/nexus3:3.74.0
    container_name: nexus
    ports:
      - 8081:8081
      - 5000:5000
    restart: no
    volumes:
      - nexus_data:/nexus-data
    networks:
      - local-default

volumes:
  nexus_data:

networks:
  local-default:
    external: true
