services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: no
    volumes:
      - ./otel-collector/ca.crt:/etc/ca.crt
      - ./otel-collector/elastic.crt:/etc/elastic.crt
      - ./otel-collector/elastic.key:/etc/elastic.key
    networks:
      - local-default

networks:
  local-default:
    external: true
