services:
  postgresql:
    container_name: postgresql
    image: postgres:17.0
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: 1
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - local-default

volumes:
  postgresql_data:

networks:
  local-default:
    external: true
