services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - 9411:9411
    restart: always
    environment:
      - STORAGE_TYPE=mem
    networks:
      - local-default

networks:
  local-default:
    external: true