version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend-net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env_mariadb
    environment:
      TZ: Asia/Seoul
    networks:
      - backend-net

  scouter-server:
    image: lislroow/scouter-server:latest
    container_name: scouter-server
    ports:
      - 6100:6100
      - 6100:6100/udp
      - 6180:6180
    restart: always
    volumes:
      - scouter_data:/apps/data
    environment:
      - SC_SERVER_ID=SCCOUTER-COLLECTOR 
      - NET_HTTP_SERVER_ENABLED=true
      - NET_HTTP_API_SWAGGER_ENABLED=true
      - NET_HTTP_API_ENABLED=true
      - MGR_PURGE_PROFILE_KEEP_DAYS=2
      - MGR_PURGE_XLOG_KEEP_DAYS=5
      - MGR_PURGE_COUNTER_KEEP_DAYS=15
      - JAVA_OPT=-Xms1024m -Xmx1024m
    networks:
      - backend-net

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.mgkim.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.mgkim.net'
    ports:
      - '9000:80'
      - '22:22'
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_conf:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
    shm_size: '256m'


volumes:
  redis_data:
  mariadb_data:
  scouter_data:
  gitlab_data:
  gitlab_logs:
  gitlab_conf:

networks:
  backend-net: