version: "3.9"
services:
  vertica:
    image: vertica/vertica-ce
    container_name: vertica-ce
    ports:
      - "5433:5433"
      - "5444:5444"
    environment:
      APP_DB_USER: "newdbadmin"
      APP_DB_PASSWORD: "vertica"
      TZ: "Asia/Seoul"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data
        target: /data
volumes:
  vertica-data:
